name: Simple Drone App Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build Build-Environment Image
      run: docker build -t portapack-dev -f dockerfile-nogit .

    - name: Compile Drone Scanner
      run: |
        docker run --rm -v ${{ github.workspace }}:/havoc portapack-dev \
        /bin/bash -c "mkdir -p build && cd build && cmake .. && make drone_scanner"

    - name: Upload App
      uses: actions/upload-artifact@v4
      with:
        name: DroneSentinelApp
        path: build/firmware/application/external/drone_scanner/*.ppma
